- hostname:
    name: "{{ inventory_hostname }}"


- name: add ssh keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - pubkeys/ruben-carbon
    - pubkeys/ruben-work
  tags:
    - ssh

- import_tasks: ssh.yml
- import_tasks: webserver.yml
